
package com.cnpe.p6.udftypeservice;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-22T15:51:21.035+08:00
 * Generated source version: 3.0.3
 * 
 */
 
public class UDFTypePortType_UDFTypePort_Server{

    protected UDFTypePortType_UDFTypePort_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new UDFTypePortImpl();
        String address = "http://10.30.7.78:8206/p6ws/services/UDFTypeService";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new UDFTypePortType_UDFTypePort_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
