
package com.cnpe.p6.activityservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:21.994+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class ActivityPortType_ActivityPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityService");

    private ActivityPortType_ActivityPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ActivityService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ActivityService ss = new ActivityService(wsdlURL, SERVICE_NAME);
        ActivityPortType port = ss.getActivityPort();  
        
        {
        System.out.println("Invoking copyActivity...");
        java.lang.Integer _copyActivity_objectIdVal = null;
        javax.xml.ws.Holder<java.lang.Integer> _copyActivity_objectId = new javax.xml.ws.Holder<java.lang.Integer>(_copyActivity_objectIdVal);
        java.lang.Integer _copyActivity_targetProjectObjectId = null;
        java.lang.Integer _copyActivity_targetWBSObjectId = null;
        java.lang.String _copyActivity_targetActivityId = "";
        java.lang.Boolean _copyActivity_copyResourceAndRoleAssignments = null;
        java.lang.Boolean _copyActivity_copyRelationships = null;
        java.lang.Boolean _copyActivity_copyActivityCodes = null;
        java.lang.Boolean _copyActivity_copyActivityNotes = null;
        java.lang.Boolean _copyActivity_copyActivityExpenses = null;
        java.lang.Boolean _copyActivity_copyActivitySteps = null;
        java.lang.Boolean _copyActivity_copyProjectDocuments = null;
        java.lang.Boolean _copyActivity_copyPastPeriodActuals = null;
        try {
            port.copyActivity(_copyActivity_objectId, _copyActivity_targetProjectObjectId, _copyActivity_targetWBSObjectId, _copyActivity_targetActivityId, _copyActivity_copyResourceAndRoleAssignments, _copyActivity_copyRelationships, _copyActivity_copyActivityCodes, _copyActivity_copyActivityNotes, _copyActivity_copyActivityExpenses, _copyActivity_copyActivitySteps, _copyActivity_copyProjectDocuments, _copyActivity_copyPastPeriodActuals);

            System.out.println("copyActivity._copyActivity_objectId=" + _copyActivity_objectId.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateActivities...");
        java.util.List<com.cnpe.p6.activityservice.Activity> _updateActivities_activity = null;
        try {
            boolean _updateActivities__return = port.updateActivities(_updateActivities_activity);
            System.out.println("updateActivities.result=" + _updateActivities__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createActivities...");
        java.util.List<com.cnpe.p6.activityservice.Activity> _createActivities_activity = null;
        try {
            java.util.List<java.lang.Integer> _createActivities__return = port.createActivities(_createActivities_activity);
            System.out.println("createActivities.result=" + _createActivities__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFieldLengthActivity...");
        java.lang.String _getFieldLengthActivity_field = "";
        try {
            int _getFieldLengthActivity__return = port.getFieldLengthActivity(_getFieldLengthActivity_field);
            System.out.println("getFieldLengthActivity.result=" + _getFieldLengthActivity__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readActivities...");
        java.util.List<com.cnpe.p6.activityservice.ActivityFieldType> _readActivities_field = null;
        java.lang.String _readActivities_filter = "";
        java.lang.String _readActivities_orderBy = "";
        try {
            java.util.List<com.cnpe.p6.activityservice.Activity> _readActivities__return = port.readActivities(_readActivities_field, _readActivities_filter, _readActivities_orderBy);
            System.out.println("readActivities.result=" + _readActivities__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteActivities...");
        java.util.List<java.lang.Integer> _deleteActivities_objectId = null;
        try {
            boolean _deleteActivities__return = port.deleteActivities(_deleteActivities_objectId);
            System.out.println("deleteActivities.result=" + _deleteActivities__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readAllActivitiesByWBS...");
        int _readAllActivitiesByWBS_wbsObjectId = 0;
        java.util.List<com.cnpe.p6.activityservice.ActivityFieldType> _readAllActivitiesByWBS_field = null;
        java.lang.String _readAllActivitiesByWBS_filter = "";
        java.lang.String _readAllActivitiesByWBS_orderBy = "";
        try {
            java.util.List<com.cnpe.p6.activityservice.Activity> _readAllActivitiesByWBS__return = port.readAllActivitiesByWBS(_readAllActivitiesByWBS_wbsObjectId, _readAllActivitiesByWBS_field, _readAllActivitiesByWBS_filter, _readAllActivitiesByWBS_orderBy);
            System.out.println("readAllActivitiesByWBS.result=" + _readAllActivitiesByWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking dissolveActivity...");
        int _dissolveActivity_objectId = 0;
        try {
            boolean _dissolveActivity__return = port.dissolveActivity(_dissolveActivity_objectId);
            System.out.println("dissolveActivity.result=" + _dissolveActivity__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
