package com.cnpe.p6.activityservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:22.054+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "ActivityService", 
                  wsdlLocation = "http://10.30.200.163:8206/p6ws/services/ActivityService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1") 
public class ActivityService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityService");
    public final static QName ActivityPort = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Activity/V1", "ActivityPort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.30.200.163:8206/p6ws/services/ActivityService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ActivityService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.30.200.163:8206/p6ws/services/ActivityService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ActivityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ActivityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ActivityService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort() {
        return super.getPort(ActivityPort, ActivityPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ActivityPortType
     */
    @WebEndpoint(name = "ActivityPort")
    public ActivityPortType getActivityPort(WebServiceFeature... features) {
        return super.getPort(ActivityPort, ActivityPortType.class, features);
    }

}
