
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cnpe.p6.authenticationservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:50:36.284+08:00
 * Generated source version: 3.0.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "AuthenticationService",
                      portName = "AuthenticationServiceSOAP12port_http",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1",
                      wsdlLocation = "http://10.30.200.163:8206/p6ws/services/AuthenticationService?wsdl",
                      endpointInterface = "com.cnpe.p6.authenticationservice.AuthenticationServicePortType")
                      
public class AuthenticationServiceSOAP12Port_HttpImpl implements AuthenticationServicePortType {

    private static final Logger LOG = Logger.getLogger(AuthenticationServiceSOAP12Port_HttpImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cnpe.p6.authenticationservice.AuthenticationServicePortType#readSessionProperties(java.lang.Object  params )*
     */
    public com.cnpe.p6.authenticationservice.ReadSessionPropertiesResponse readSessionProperties(java.lang.Object params) throws IntegrationFault    { 
        LOG.info("Executing operation readSessionProperties");
        System.out.println(params);
        try {
            com.cnpe.p6.authenticationservice.ReadSessionPropertiesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.authenticationservice.AuthenticationServicePortType#readDatabaseInstances(java.lang.Object  params )*
     */
    public com.cnpe.p6.authenticationservice.ReadDatabaseInstancesResponse readDatabaseInstances(java.lang.Object params) throws IntegrationFault    { 
        LOG.info("Executing operation readDatabaseInstances");
        System.out.println(params);
        try {
            com.cnpe.p6.authenticationservice.ReadDatabaseInstancesResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.authenticationservice.AuthenticationServicePortType#login(java.lang.String  userName ,)java.lang.String  password ,)java.lang.Integer  databaseInstanceId )*
     */
    public java.lang.Boolean login(java.lang.String userName,java.lang.String password,java.lang.Integer databaseInstanceId) throws IntegrationFault    { 
        LOG.info("Executing operation login");
        System.out.println(userName);
        System.out.println(password);
        System.out.println(databaseInstanceId);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.authenticationservice.AuthenticationServicePortType#updateSessionProperties(java.lang.Boolean  ignoreNullComplexFields )*
     */
    public java.lang.Boolean updateSessionProperties(java.lang.Boolean ignoreNullComplexFields) { 
        LOG.info("Executing operation updateSessionProperties");
        System.out.println(ignoreNullComplexFields);
        try {
            java.lang.Boolean _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.authenticationservice.AuthenticationServicePortType#logout(java.lang.Object  params )*
     */
    public com.cnpe.p6.authenticationservice.LogoutResponse logout(java.lang.Object params) { 
        LOG.info("Executing operation logout");
        System.out.println(params);
        try {
            com.cnpe.p6.authenticationservice.LogoutResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
