
package com.cnpe.p6.authenticationservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:50:36.250+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class AuthenticationServicePortType_AuthenticationServiceSOAP12PortHttp_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/Authentication/V1", "AuthenticationService");

    private AuthenticationServicePortType_AuthenticationServiceSOAP12PortHttp_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = AuthenticationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        AuthenticationService ss = new AuthenticationService(wsdlURL, SERVICE_NAME);
        AuthenticationServicePortType port = ss.getAuthenticationServiceSOAP12PortHttp();  
        
        {
        System.out.println("Invoking readSessionProperties...");
        java.lang.Object _readSessionProperties_params = new java.lang.Object();
        try {
            com.cnpe.p6.authenticationservice.ReadSessionPropertiesResponse _readSessionProperties__return = port.readSessionProperties(_readSessionProperties_params);
            System.out.println("readSessionProperties.result=" + _readSessionProperties__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readDatabaseInstances...");
        java.lang.Object _readDatabaseInstances_params = new java.lang.Object();
        try {
            com.cnpe.p6.authenticationservice.ReadDatabaseInstancesResponse _readDatabaseInstances__return = port.readDatabaseInstances(_readDatabaseInstances_params);
            System.out.println("readDatabaseInstances.result=" + _readDatabaseInstances__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking login...");
        java.lang.String _login_userName = "";
        java.lang.String _login_password = "";
        java.lang.Integer _login_databaseInstanceId = null;
        try {
            java.lang.Boolean _login__return = port.login(_login_userName, _login_password, _login_databaseInstanceId);
            System.out.println("login.result=" + _login__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateSessionProperties...");
        java.lang.Boolean _updateSessionProperties_ignoreNullComplexFields = null;
        java.lang.Boolean _updateSessionProperties__return = port.updateSessionProperties(_updateSessionProperties_ignoreNullComplexFields);
        System.out.println("updateSessionProperties.result=" + _updateSessionProperties__return);


        }
        {
        System.out.println("Invoking logout...");
        java.lang.Object _logout_params = new java.lang.Object();
        com.cnpe.p6.authenticationservice.LogoutResponse _logout__return = port.logout(_logout_params);
        System.out.println("logout.result=" + _logout__return);


        }

        System.exit(0);
    }

}
