package com.cnpe.p6.projectservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:03.451+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", name = "ProjectPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectPortType {

    @WebResult(name = "ResourceObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "LoadAllResources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadAllResources")
    @WebMethod(operationName = "LoadAllResources", action = "LoadAllResources")
    @ResponseWrapper(localName = "LoadAllResourcesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadAllResourcesResponse")
    public java.util.List<java.lang.String> loadAllResources(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String orderBy
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CopyWBSFromTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyWBSFromTemplate")
    @WebMethod(operationName = "CopyWBSFromTemplate", action = "CopyWBSFromTemplate")
    @ResponseWrapper(localName = "CopyWBSFromTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyWBSFromTemplateResponse")
    public void copyWBSFromTemplate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "TemplateWbsObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int templateWbsObjectId
    ) throws IntegrationFault;

    @WebResult(name = "BaselineProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "AssignProjectAsBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.AssignProjectAsBaseline")
    @WebMethod(operationName = "AssignProjectAsBaseline", action = "AssignProjectAsBaseline")
    @ResponseWrapper(localName = "AssignProjectAsBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.AssignProjectAsBaselineResponse")
    public int assignProjectAsBaseline(
        @WebParam(name = "OriginalProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int originalProjectObjectId,
        @WebParam(name = "TargetProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int targetProjectObjectId
    ) throws IntegrationFault;

    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "CreateProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateProjects")
    @WebMethod(operationName = "CreateProjects", action = "CreateProjects")
    @ResponseWrapper(localName = "CreateProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateProjectsResponse")
    public java.util.List<java.lang.Integer> createProjects(
        @WebParam(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<com.cnpe.p6.projectservice.Project> project
    ) throws IntegrationFault;

    @WebResult(name = "BaselineProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "ConvertProjectToBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.ConvertProjectToBaseline")
    @WebMethod(operationName = "ConvertProjectToBaseline", action = "ConvertProjectToBaseline")
    @ResponseWrapper(localName = "ConvertProjectToBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.ConvertProjectToBaselineResponse")
    public int convertProjectToBaseline(
        @WebParam(name = "OriginalProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int originalProjectObjectId,
        @WebParam(name = "TargetProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int targetProjectObjectId
    ) throws IntegrationFault;

    @WebResult(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "ReadProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.ReadProjects")
    @WebMethod(operationName = "ReadProjects", action = "ReadProjects")
    @ResponseWrapper(localName = "ReadProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.ReadProjectsResponse")
    public java.util.List<com.cnpe.p6.projectservice.Project> readProjects(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.String> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String orderBy
    ) throws IntegrationFault;

    @WebResult(name = "UDFValueObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "LoadActivityUDFValuesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivityUDFValuesNewerThanBaseline")
    @WebMethod(operationName = "LoadActivityUDFValuesNewerThanBaseline", action = "LoadActivityUDFValuesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivityUDFValuesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivityUDFValuesNewerThanBaselineResponse")
    public java.util.List<java.lang.String> loadActivityUDFValuesNewerThanBaseline(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CopyProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProject")
    @WebMethod(operationName = "CopyProject", action = "CopyProject")
    @ResponseWrapper(localName = "CopyProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProjectResponse")
    public void copyProject(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectNotes,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyPastPeriodActuals
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "getFieldLengthProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.GetFieldLengthProject")
    @WebMethod(action = "getFieldLengthProject")
    @ResponseWrapper(localName = "getFieldLengthProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.GetFieldLengthProjectResponse")
    public int getFieldLengthProject(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String field
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "UpdateProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.UpdateProjects")
    @WebMethod(operationName = "UpdateProjects", action = "UpdateProjects")
    @ResponseWrapper(localName = "UpdateProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.UpdateProjectsResponse")
    public boolean updateProjects(
        @WebParam(name = "Project", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<com.cnpe.p6.projectservice.Project> project
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CopyProjectAsReflection", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProjectAsReflection")
    @WebMethod(operationName = "CopyProjectAsReflection", action = "CopyProjectAsReflection")
    @ResponseWrapper(localName = "CopyProjectAsReflectionResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProjectAsReflectionResponse")
    public void copyProjectAsReflection(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CreateCopyAsTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateCopyAsTemplate")
    @WebMethod(operationName = "CreateCopyAsTemplate", action = "CreateCopyAsTemplate")
    @ResponseWrapper(localName = "CreateCopyAsTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateCopyAsTemplateResponse")
    public void createCopyAsTemplate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectNotes,
        @WebParam(name = "CopyActualToPlannedValues", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActualToPlannedValues,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyPastPeriodActuals
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CopyBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyBaseline")
    @WebMethod(operationName = "CopyBaseline", action = "CopyBaseline")
    @ResponseWrapper(localName = "CopyBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyBaselineResponse")
    public void copyBaseline(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @WebResult(name = "ActivityObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "LoadActivitiesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivitiesNewerThanBaseline")
    @WebMethod(operationName = "LoadActivitiesNewerThanBaseline", action = "LoadActivitiesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivitiesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivitiesNewerThanBaselineResponse")
    public java.util.List<java.lang.String> loadActivitiesNewerThanBaseline(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CreateProjectFromTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateProjectFromTemplate")
    @WebMethod(operationName = "CreateProjectFromTemplate", action = "CreateProjectFromTemplate")
    @ResponseWrapper(localName = "CreateProjectFromTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CreateProjectFromTemplateResponse")
    public void createProjectFromTemplate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "EPSObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int epsObjectId,
        @WebParam(name = "CopyRisks", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRisks,
        @WebParam(name = "CopyIssuesThresholds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyIssuesThresholds,
        @WebParam(name = "CopyReports", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyReports,
        @WebParam(name = "CopyProjectDocuments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectDocuments,
        @WebParam(name = "CopyFundingSources", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyFundingSources,
        @WebParam(name = "CopySummaryData", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copySummaryData,
        @WebParam(name = "CopyProjectNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyProjectNotes,
        @WebParam(name = "CopyWBSMilestones", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyWBSMilestones,
        @WebParam(name = "CopyActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivities,
        @WebParam(name = "CopyHighLevelResourcePlanning", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyHighLevelResourcePlanning,
        @WebParam(name = "CopyResourceAndRoleAssignments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyResourceAndRoleAssignments,
        @WebParam(name = "CopyRelationships", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyRelationships,
        @WebParam(name = "CopyOnlyBetweenCopiedActivities", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyOnlyBetweenCopiedActivities,
        @WebParam(name = "CopyActivityExpenses", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityExpenses,
        @WebParam(name = "CopyActivityCodes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityCodes,
        @WebParam(name = "CopyActivityNotes", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivityNotes,
        @WebParam(name = "CopyActivitySteps", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyActivitySteps,
        @WebParam(name = "CopyPastPeriodActuals", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean copyPastPeriodActuals
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "UpdateProjectPreferences", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.UpdateProjectPreferences")
    @WebMethod(operationName = "UpdateProjectPreferences", action = "UpdateProjectPreferences")
    @ResponseWrapper(localName = "UpdateProjectPreferencesResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.UpdateProjectPreferencesResponse")
    public boolean updateProjectPreferences(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "EnablePublication", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean enablePublication,
        @WebParam(name = "PublicationPriority", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Integer publicationPriority,
        @WebParam(name = "LastPublishedOn", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String lastPublishedOn,
        @WebParam(name = "PublishLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String publishLevel,
        @WebParam(name = "DeploymentNames", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String deploymentNames,
        @WebParam(name = "DeleteDeployments", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String deleteDeployments,
        @WebParam(name = "UnifierEnabledFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean unifierEnabledFlag,
        @WebParam(name = "UnifierProjectNumber", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String unifierProjectNumber,
        @WebParam(name = "UnifierProjectName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String unifierProjectName,
        @WebParam(name = "UnifierScheduleSheetName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String unifierScheduleSheetName,
        @WebParam(name = "UnifierDataMappingName", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String unifierDataMappingName,
        @WebParam(name = "UnifierDeleteActivitiesFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean unifierDeleteActivitiesFlag,
        @WebParam(name = "UnifierCBSTasksOnlyFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean unifierCBSTasksOnlyFlag,
        @WebParam(name = "ProjectScheduleType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String projectScheduleType,
        @WebParam(name = "SyncWbsHierarchyFlag", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean syncWbsHierarchyFlag,
        @WebParam(name = "ScheduleWBSHierarchyType", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String scheduleWBSHierarchyType,
        @WebParam(name = "WBSHierarchyLevels", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Integer wbsHierarchyLevels,
        @WebParam(name = "EnableSummarization", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Boolean enableSummarization,
        @WebParam(name = "SummaryLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String summaryLevel,
        @WebParam(name = "SummarizeToWBSLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.Integer summarizeToWBSLevel,
        @WebParam(name = "LastSummarizedDate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String lastSummarizedDate,
        @WebParam(name = "HistoryLevel", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String historyLevel,
        @WebParam(name = "HistoryInterval", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String historyInterval
    ) throws IntegrationFault;

    @WebResult(name = "ActivityCodeAssignmentObjectIds", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "LoadActivityCodesNewerThanBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivityCodesNewerThanBaseline")
    @WebMethod(operationName = "LoadActivityCodesNewerThanBaseline", action = "LoadActivityCodesNewerThanBaseline")
    @ResponseWrapper(localName = "LoadActivityCodesNewerThanBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.LoadActivityCodesNewerThanBaselineResponse")
    public java.util.List<java.lang.String> loadActivityCodesNewerThanBaseline(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "Fields", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.String> fields,
        @WebParam(name = "WhereClause", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String whereClause,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.lang.String orderBy,
        @WebParam(name = "BaselineObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int baselineObjectId
    ) throws IntegrationFault;

    @WebResult(name = "Success", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "IsProjectLocked", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.IsProjectLocked")
    @WebMethod(operationName = "IsProjectLocked", action = "IsProjectLocked")
    @ResponseWrapper(localName = "IsProjectLockedResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.IsProjectLockedResponse")
    public boolean isProjectLocked(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId,
        @WebParam(name = "IncludeCurrentSession", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        boolean includeCurrentSession
    ) throws IntegrationFault;

    @WebResult(name = "Score", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "CalculateProjectScore", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CalculateProjectScore")
    @WebMethod(operationName = "CalculateProjectScore", action = "CalculateProjectScore")
    @ResponseWrapper(localName = "CalculateProjectScoreResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CalculateProjectScoreResponse")
    public int calculateProjectScore(
        @WebParam(name = "ProjectObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int projectObjectId,
        @WebParam(name = "ProjectCodeTypeObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.Integer> projectCodeTypeObjectId
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "PublishProject", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.PublishProject")
    @WebMethod(operationName = "PublishProject", action = "PublishProject")
    @ResponseWrapper(localName = "PublishProjectResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.PublishProjectResponse")
    public boolean publishProject(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        int objectId
    ) throws IntegrationFault;

    @RequestWrapper(localName = "CopyProjectAsBaseline", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProjectAsBaseline")
    @WebMethod(operationName = "CopyProjectAsBaseline", action = "CopyProjectAsBaseline")
    @ResponseWrapper(localName = "CopyProjectAsBaselineResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.CopyProjectAsBaselineResponse")
    public void copyProjectAsBaseline(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
    @RequestWrapper(localName = "DeleteProjects", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.DeleteProjects")
    @WebMethod(operationName = "DeleteProjects", action = "DeleteProjects")
    @ResponseWrapper(localName = "DeleteProjectsResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2", className = "com.cnpe.p6.projectservice.DeleteProjectsResponse")
    public boolean deleteProjects(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/Project/V2")
        java.util.List<java.lang.Integer> objectId
    ) throws IntegrationFault;
}
