
package com.cnpe.p6.wbsservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:12.248+08:00
 * Generated source version: 3.0.3
 * 
 */
public final class WBSPortType_WBSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", "WBSService");

    private WBSPortType_WBSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WBSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WBSService ss = new WBSService(wsdlURL, SERVICE_NAME);
        WBSPortType port = ss.getWBSPort();  
        
        {
        System.out.println("Invoking copyWBSFromTemplate...");
        java.lang.Integer _copyWBSFromTemplate_objectIdVal = null;
        javax.xml.ws.Holder<java.lang.Integer> _copyWBSFromTemplate_objectId = new javax.xml.ws.Holder<java.lang.Integer>(_copyWBSFromTemplate_objectIdVal);
        int _copyWBSFromTemplate_templateWbsObjectId = 0;
        try {
            port.copyWBSFromTemplate(_copyWBSFromTemplate_objectId, _copyWBSFromTemplate_templateWbsObjectId);

            System.out.println("copyWBSFromTemplate._copyWBSFromTemplate_objectId=" + _copyWBSFromTemplate_objectId.value);
        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getFieldLengthWBS...");
        java.lang.String _getFieldLengthWBS_field = "";
        try {
            int _getFieldLengthWBS__return = port.getFieldLengthWBS(_getFieldLengthWBS_field);
            System.out.println("getFieldLengthWBS.result=" + _getFieldLengthWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readWBS...");
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> _readWBS_field = null;
        java.lang.String _readWBS_filter = "";
        java.lang.String _readWBS_orderBy = "";
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _readWBS__return = port.readWBS(_readWBS_field, _readWBS_filter, _readWBS_orderBy);
            System.out.println("readWBS.result=" + _readWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readAllWBS...");
        int _readAllWBS_objectId = 0;
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> _readAllWBS_field = null;
        java.lang.String _readAllWBS_filter = "";
        java.lang.String _readAllWBS_orderBy = "";
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _readAllWBS__return = port.readAllWBS(_readAllWBS_objectId, _readAllWBS_field, _readAllWBS_filter, _readAllWBS_orderBy);
            System.out.println("readAllWBS.result=" + _readAllWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readActivityWBSPath...");
        java.util.List<java.lang.Integer> _readActivityWBSPath_activityObjectId = null;
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> _readActivityWBSPath_field = null;
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _readActivityWBSPath__return = port.readActivityWBSPath(_readActivityWBSPath_activityObjectId, _readActivityWBSPath_field);
            System.out.println("readActivityWBSPath.result=" + _readActivityWBSPath__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking updateWBS...");
        java.util.List<com.cnpe.p6.wbsservice.WBS> _updateWBS_wbs = null;
        try {
            boolean _updateWBS__return = port.updateWBS(_updateWBS_wbs);
            System.out.println("updateWBS.result=" + _updateWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking createWBS...");
        java.util.List<com.cnpe.p6.wbsservice.WBS> _createWBS_wbs = null;
        try {
            java.util.List<java.lang.Integer> _createWBS__return = port.createWBS(_createWBS_wbs);
            System.out.println("createWBS.result=" + _createWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking deleteWBS...");
        java.util.List<java.lang.Integer> _deleteWBS_objectId = null;
        java.util.List<com.cnpe.p6.wbsservice.DeleteWBS.DeleteWithReplacement> _deleteWBS_deleteWithReplacement = null;
        try {
            boolean _deleteWBS__return = port.deleteWBS(_deleteWBS_objectId, _deleteWBS_deleteWithReplacement);
            System.out.println("deleteWBS.result=" + _deleteWBS__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking readWBSPath...");
        java.util.List<java.lang.Integer> _readWBSPath_objectId = null;
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> _readWBSPath_field = null;
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _readWBSPath__return = port.readWBSPath(_readWBSPath_objectId, _readWBSPath_field);
            System.out.println("readWBSPath.result=" + _readWBSPath__return);

        } catch (IntegrationFault e) { 
            System.out.println("Expected exception: IntegrationFault has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
