
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cnpe.p6.wbsservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:12.289+08:00
 * Generated source version: 3.0.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "WBSService",
                      portName = "WBSPort",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2",
                      wsdlLocation = "http://10.30.200.163:8206/p6ws/services/WBSService?wsdl",
                      endpointInterface = "com.cnpe.p6.wbsservice.WBSPortType")
                      
public class WBSPortImpl implements WBSPortType {

    private static final Logger LOG = Logger.getLogger(WBSPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#copyWBSFromTemplate(java.lang.Integer  objectId ,)int  templateWbsObjectId )*
     */
    public void copyWBSFromTemplate(javax.xml.ws.Holder<java.lang.Integer> objectId,int templateWbsObjectId) throws IntegrationFault    { 
        LOG.info("Executing operation copyWBSFromTemplate");
        System.out.println(objectId.value);
        System.out.println(templateWbsObjectId);
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#getFieldLengthWBS(java.lang.String  field )*
     */
    public int getFieldLengthWBS(java.lang.String field) throws IntegrationFault    { 
        LOG.info("Executing operation getFieldLengthWBS");
        System.out.println(field);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#readWBS(java.util.List<com.cnpe.p6.wbsservice.WBSFieldType>  field ,)java.lang.String  filter ,)java.lang.String  orderBy )*
     */
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readWBS(java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field,java.lang.String filter,java.lang.String orderBy) throws IntegrationFault    { 
        LOG.info("Executing operation readWBS");
        System.out.println(field);
        System.out.println(filter);
        System.out.println(orderBy);
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#readAllWBS(int  objectId ,)java.util.List<com.cnpe.p6.wbsservice.WBSFieldType>  field ,)java.lang.String  filter ,)java.lang.String  orderBy )*
     */
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readAllWBS(int objectId,java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field,java.lang.String filter,java.lang.String orderBy) throws IntegrationFault    { 
        LOG.info("Executing operation readAllWBS");
        System.out.println(objectId);
        System.out.println(field);
        System.out.println(filter);
        System.out.println(orderBy);
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#readActivityWBSPath(java.util.List<java.lang.Integer>  activityObjectId ,)java.util.List<com.cnpe.p6.wbsservice.WBSFieldType>  field )*
     */
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readActivityWBSPath(java.util.List<java.lang.Integer> activityObjectId,java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field) throws IntegrationFault    { 
        LOG.info("Executing operation readActivityWBSPath");
        System.out.println(activityObjectId);
        System.out.println(field);
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#updateWBS(java.util.List<com.cnpe.p6.wbsservice.WBS>  wbs )*
     */
    public boolean updateWBS(java.util.List<com.cnpe.p6.wbsservice.WBS> wbs) throws IntegrationFault    { 
        LOG.info("Executing operation updateWBS");
        System.out.println(wbs);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#createWBS(java.util.List<com.cnpe.p6.wbsservice.WBS>  wbs )*
     */
    public java.util.List<java.lang.Integer> createWBS(java.util.List<com.cnpe.p6.wbsservice.WBS> wbs) throws IntegrationFault    { 
        LOG.info("Executing operation createWBS");
        System.out.println(wbs);
        try {
            java.util.List<java.lang.Integer> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#deleteWBS(java.util.List<java.lang.Integer>  objectId ,)java.util.List<com.cnpe.p6.wbsservice.DeleteWBS.DeleteWithReplacement>  deleteWithReplacement )*
     */
    public boolean deleteWBS(java.util.List<java.lang.Integer> objectId,java.util.List<com.cnpe.p6.wbsservice.DeleteWBS.DeleteWithReplacement> deleteWithReplacement) throws IntegrationFault    { 
        LOG.info("Executing operation deleteWBS");
        System.out.println(objectId);
        System.out.println(deleteWithReplacement);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.wbsservice.WBSPortType#readWBSPath(java.util.List<java.lang.Integer>  objectId ,)java.util.List<com.cnpe.p6.wbsservice.WBSFieldType>  field )*
     */
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readWBSPath(java.util.List<java.lang.Integer> objectId,java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field) throws IntegrationFault    { 
        LOG.info("Executing operation readWBSPath");
        System.out.println(objectId);
        System.out.println(field);
        try {
            java.util.List<com.cnpe.p6.wbsservice.WBS> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

}
