package com.cnpe.p6.wbsservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:51:12.302+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", name = "WBSPortType")
@XmlSeeAlso({ObjectFactory.class})
public interface WBSPortType {

    @RequestWrapper(localName = "CopyWBSFromTemplate", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.CopyWBSFromTemplate")
    @WebMethod(operationName = "CopyWBSFromTemplate", action = "CopyWBSFromTemplate")
    @ResponseWrapper(localName = "CopyWBSFromTemplateResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.CopyWBSFromTemplateResponse")
    public void copyWBSFromTemplate(
        @WebParam(mode = WebParam.Mode.INOUT, name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        javax.xml.ws.Holder<java.lang.Integer> objectId,
        @WebParam(name = "TemplateWbsObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        int templateWbsObjectId
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "getFieldLengthWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.GetFieldLengthWBS")
    @WebMethod(action = "getFieldLengthWBS")
    @ResponseWrapper(localName = "getFieldLengthWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.GetFieldLengthWBSResponse")
    public int getFieldLengthWBS(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.lang.String field
    ) throws IntegrationFault;

    @WebResult(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "ReadWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadWBS")
    @WebMethod(operationName = "ReadWBS", action = "ReadWBS")
    @ResponseWrapper(localName = "ReadWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadWBSResponse")
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readWBS(
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.lang.String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.lang.String orderBy
    ) throws IntegrationFault;

    @WebResult(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "ReadAllWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadAllWBS")
    @WebMethod(operationName = "ReadAllWBS", action = "ReadAllWBS")
    @ResponseWrapper(localName = "ReadAllWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadAllWBSResponse")
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readAllWBS(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        int objectId,
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field,
        @WebParam(name = "Filter", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.lang.String filter,
        @WebParam(name = "OrderBy", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.lang.String orderBy
    ) throws IntegrationFault;

    @WebResult(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "ReadActivityWBSPath", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadActivityWBSPath")
    @WebMethod(operationName = "ReadActivityWBSPath", action = "ReadActivityWBSPath")
    @ResponseWrapper(localName = "ReadActivityWBSPathResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadActivityWBSPathResponse")
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readActivityWBSPath(
        @WebParam(name = "ActivityObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<java.lang.Integer> activityObjectId,
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "UpdateWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.UpdateWBS")
    @WebMethod(operationName = "UpdateWBS", action = "UpdateWBS")
    @ResponseWrapper(localName = "UpdateWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.UpdateWBSResponse")
    public boolean updateWBS(
        @WebParam(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBS> wbs
    ) throws IntegrationFault;

    @WebResult(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "CreateWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.CreateWBS")
    @WebMethod(operationName = "CreateWBS", action = "CreateWBS")
    @ResponseWrapper(localName = "CreateWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.CreateWBSResponse")
    public java.util.List<java.lang.Integer> createWBS(
        @WebParam(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBS> wbs
    ) throws IntegrationFault;

    @WebResult(name = "Return", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "DeleteWBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.DeleteWBS")
    @WebMethod(operationName = "DeleteWBS", action = "DeleteWBS")
    @ResponseWrapper(localName = "DeleteWBSResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.DeleteWBSResponse")
    public boolean deleteWBS(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<java.lang.Integer> objectId,
        @WebParam(name = "DeleteWithReplacement", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.DeleteWBS.DeleteWithReplacement> deleteWithReplacement
    ) throws IntegrationFault;

    @WebResult(name = "WBS", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
    @RequestWrapper(localName = "ReadWBSPath", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadWBSPath")
    @WebMethod(operationName = "ReadWBSPath", action = "ReadWBSPath")
    @ResponseWrapper(localName = "ReadWBSPathResponse", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2", className = "com.cnpe.p6.wbsservice.ReadWBSPathResponse")
    public java.util.List<com.cnpe.p6.wbsservice.WBS> readWBSPath(
        @WebParam(name = "ObjectId", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<java.lang.Integer> objectId,
        @WebParam(name = "Field", targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/WBS/V2")
        java.util.List<com.cnpe.p6.wbsservice.WBSFieldType> field
    ) throws IntegrationFault;
}
