
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.cnpe.p6.udfvalueservice;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:50:45.039+08:00
 * Generated source version: 3.0.3
 * 
 */

@javax.jws.WebService(
                      serviceName = "UDFValueService",
                      portName = "UDFValuePort",
                      targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1",
                      wsdlLocation = "http://10.30.200.163:8206/p6ws/services/UDFValueService?wsdl",
                      endpointInterface = "com.cnpe.p6.udfvalueservice.UDFValuePortType")
                      
public class UDFValuePortImpl implements UDFValuePortType {

    private static final Logger LOG = Logger.getLogger(UDFValuePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#updateUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValue>  udfValue )*
     */
    public boolean updateUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValue> udfValue) throws IntegrationFault    { 
        LOG.info("Executing operation updateUDFValues");
        System.out.println(udfValue);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#readUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValueFieldType>  field ,)java.lang.String  filter ,)java.lang.String  orderBy )*
     */
    public java.util.List<com.cnpe.p6.udfvalueservice.UDFValue> readUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValueFieldType> field,java.lang.String filter,java.lang.String orderBy) throws IntegrationFault    { 
        LOG.info("Executing operation readUDFValues");
        System.out.println(field);
        System.out.println(filter);
        System.out.println(orderBy);
        try {
            java.util.List<com.cnpe.p6.udfvalueservice.UDFValue> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#readCalculatedUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.CalculatedUDFValueFieldType>  field ,)java.util.List<java.lang.Integer>  udfTypeObjectId ,)java.util.List<java.lang.Integer>  projectObjectId )*
     */
    public java.util.List<com.cnpe.p6.udfvalueservice.ReadCalculatedUDFValuesResponse.CalculatedUDFValue> readCalculatedUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.CalculatedUDFValueFieldType> field,java.util.List<java.lang.Integer> udfTypeObjectId,java.util.List<java.lang.Integer> projectObjectId) throws IntegrationFault    { 
        LOG.info("Executing operation readCalculatedUDFValues");
        System.out.println(field);
        System.out.println(udfTypeObjectId);
        System.out.println(projectObjectId);
        try {
            java.util.List<com.cnpe.p6.udfvalueservice.ReadCalculatedUDFValuesResponse.CalculatedUDFValue> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#deleteUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.DeleteUDFValues.ObjectId>  objectId )*
     */
    public boolean deleteUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.DeleteUDFValues.ObjectId> objectId) throws IntegrationFault    { 
        LOG.info("Executing operation deleteUDFValues");
        System.out.println(objectId);
        try {
            boolean _return = false;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#getFieldLengthUDFValue(java.lang.String  field )*
     */
    public int getFieldLengthUDFValue(java.lang.String field) throws IntegrationFault    { 
        LOG.info("Executing operation getFieldLengthUDFValue");
        System.out.println(field);
        try {
            int _return = 0;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

    /* (non-Javadoc)
     * @see com.cnpe.p6.udfvalueservice.UDFValuePortType#createUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValue>  udfValue )*
     */
    public java.util.List<com.cnpe.p6.udfvalueservice.CreateUDFValuesResponse.ObjectId> createUDFValues(java.util.List<com.cnpe.p6.udfvalueservice.UDFValue> udfValue) throws IntegrationFault    { 
        LOG.info("Executing operation createUDFValues");
        System.out.println(udfValue);
        try {
            java.util.List<com.cnpe.p6.udfvalueservice.CreateUDFValuesResponse.ObjectId> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
        //throw new IntegrationFault("IntegrationFault...");
    }

}
