package com.cnpe.p6.udfvalueservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2020-07-08T18:50:45.082+08:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "UDFValueService", 
                  wsdlLocation = "http://10.30.200.163:8206/p6ws/services/UDFValueService?wsdl",
                  targetNamespace = "http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1") 
public class UDFValueService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", "UDFValueService");
    public final static QName UDFValuePort = new QName("http://xmlns.oracle.com/Primavera/P6/WS/UDFValue/V1", "UDFValuePort");
    static {
        URL url = null;
        try {
            url = new URL("http://10.30.200.163:8206/p6ws/services/UDFValueService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UDFValueService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://10.30.200.163:8206/p6ws/services/UDFValueService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UDFValueService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UDFValueService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UDFValueService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UDFValuePortType
     */
    @WebEndpoint(name = "UDFValuePort")
    public UDFValuePortType getUDFValuePort() {
        return super.getPort(UDFValuePort, UDFValuePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UDFValuePortType
     */
    @WebEndpoint(name = "UDFValuePort")
    public UDFValuePortType getUDFValuePort(WebServiceFeature... features) {
        return super.getPort(UDFValuePort, UDFValuePortType.class, features);
    }

}
